- name: Install To-Do App on new web server
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - name: Install Git and Python
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
        - python3-pip
      become: yes
    - name: Install Poetry
      pip:
        name: poetry
        executable: pip3
    - name: Create /opt/todoapp directory
      file:
        path: /opt/todoapp
        state: directory
        mode: 0755
      become: yes
    - name: Set ec2-user as owner of /opt/todoapp directory
      file:
        path: /opt/todoapp
        owner: ec2-user
        group: ec2-user
        recurse: yes
      become: yes
    - name: Store git repo in todoapp folder
      git:
        repo: https://github.com/ClaHur/DevOps-Course-Starter.git
        dest: /opt/todoapp
        version: remote-branch
      become: yes
    - name: Change directory to /opt/todoapp
      shell: cd /opt/todoapp
    - name: Run poetry install
      shell: poetry install
      args:
        chdir: /opt/todoapp
    - name: Create .env file
      template:
        src: .env.j2
        dest: /opt/todoapp/.env
    - name: Copy todoapp.service to host
      template:
        src: todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes
    - name: Start todo app
      systemd:
        name: todoapp
        daemon_reload: yes
        state: restarted
      become: yes
  vars_prompt:
      - name: "trello_api_key"
        prompt: "Enter your Trello API key"
        private: no
      - name: "trello_token"
        prompt: "Enter your Trello token"
        private: yes
      - name: "trello_board_id"
        prompt: "Enter your Trello board ID"
        private: no