- name: Install To-Do App on new web server
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - name: Install Git and Python
      yum:
        name: 
          - git
          - python3
          - python3-pip
        state: present
      become: yes
    - name: Install Poetry
      pip:
        name: poetry
        executable: pip3
    - name: Create /opt/todoapp directory
      file:
        path: /opt/todoapp
        state: directory
        mode: 0755
        owner: ec2-user
        group: ec2-user
        recurse: yes
      become: yes

    - name: Store git repo in todoapp folder
      git:
        repo: https://github.com/ClaHur/DevOps-Course-Starter.git
        dest: /opt/todoapp
        version: remote-branch
      become: yes
    - name: Run poetry install
      shell: poetry install
      args:
        chdir: /opt/todoapp
    - name: Create .env file
      template:
        src: .env.j2
        dest: /opt/todoapp/.env
    - name: Copy todoapp.service to host
      template:
        src: todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes
    - name: Start todo app
      systemd:
        name: todoapp
        daemon_reload: yes
        state: restarted
      become: yes
  vars_prompt:
      - name: "mongodb_primary_connection"
        prompt: "Enter your Mongo DB primary connection string"
        private: no