name: Continuous Integration
on:
  push:
    paths-ignore:
      - '.github/**'
      - './ansible/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - './ansible/**'
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target test --tag todo-app:test .
      - run: docker run todo-app:test

  push_to_dockerhub:
    name: Push docker image and deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
         docker build --target production --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest \
                      --target production --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }} .

      - name: Push Docker image
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app --all-tags

      - name: Deploy to Azure
        run: curl -v -X POST '${{ secrets.WEBHOOK_URL }}'
