name: Continuous Integration
on:
  push:
    paths-ignore:
      - '.github/**'
      - './ansible/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - './ansible/**'
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test